"""initial schema"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_proposals',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('proposal_type', sa.Enum('add_provider_series', 'add_derived_series', 'add_family', 'add_concept', 'code_and_db_change', 'schema_change', 'mixed', name='ck_change_proposals_proposal_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'applied', 'rejected', 'failed', 'superseded', name='ck_change_proposals_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_by', sa.Enum('user', 'agent', 'system', name='ck_change_proposals_requested_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by_agent', sa.String(), nullable=True),
    sa.Column('user_prompt', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='ck_change_proposals_risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_proposal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_proposal_id'], ['change_proposals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_concepts_code')
    )
    op.create_table('geographies',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alt_name', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('type', sa.Enum('country', 'subnational', 'subnational_region', 'region', 'bloc', 'world', name='ck_geographies_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('code_standard', sa.Enum('ISO 3166-1', 'ISO 3166-2', 'WB', 'internal', name='ck_geographies_code_standard', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('parent_geography_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type NOT IN ('subnational', 'subnational_region')) OR parent_geography_id IS NOT NULL", name='ck_geographies_type_requires_parent'),
    sa.ForeignKeyConstraint(['parent_geography_id'], ['geographies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_geographies_code')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alt_name', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('type', sa.Enum('official', 'international_organization', 'vendor', 'internal', 'other', name='ck_providers_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('doc_url', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('credentials_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_providers_name')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('change_proposal_items',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('db_row', 'code_change', 'migration', 'test', 'validation', 'documentation', name='ck_change_proposal_items_item_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_type', sa.Enum('concepts', 'series', 'series_families', 'series_sources', 'ingestion_feeds', 'file', 'function', 'test', 'providers', 'provider_catalogs', 'derived_series', 'derivation_inputs', 'geographies', 'tags', 'series_family_members', 'geography_memberships', name='ck_change_proposal_items_target_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('action', sa.Enum('insert', 'update', 'deactivate', 'create_file', 'modify_file', 'run_test', 'validate', name='ck_change_proposal_items_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_ref', sa.String(), nullable=True),
    sa.Column('proposed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_summary', sa.String(), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'passed', 'failed', 'warning', 'not_required', name='ck_change_proposal_items_validation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('validation_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['change_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geography_memberships',
    sa.Column('member_geography_id', sa.UUID(), nullable=False),
    sa.Column('group_geography_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_geography_id'], ['geographies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_geography_id'], ['geographies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_catalogs',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('catalog_url', sa.String(), nullable=True),
    sa.Column('doc_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('origin_type', sa.Enum('ingested', 'derived', 'both', name='ck_series_origin_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('geography_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('D', 'W', 'M', 'Q', 'S', 'A', name='ck_series_frequency', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('temporal_stock_flow', sa.Enum('stock', 'flow', 'rate', 'index', 'unknown', name='ck_series_temporal_stock_flow', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit_kind', sa.Enum('index', 'percent', 'bps', 'currency', 'count', 'quantity', 'ratio', 'none', name='ck_series_unit_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit_scale', sa.Enum('one', 'thousand', 'million', 'billion', 'trillion', name='ck_series_unit_scale', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit_label', sa.String(), nullable=True),
    sa.Column('price_basis', sa.Enum('nominal', 'real', 'ppp', 'other', name='ck_series_price_basis', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('measure', sa.Enum('level', 'growth', 'change', name='ck_series_measure', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('measure_horizon', sa.Enum('ytd', 'wow', 'mom', 'qoq', 'yoy', 'custom', name='ck_series_measure_horizon', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('annualized', sa.Boolean(), nullable=False),
    sa.Column('seasonal_adjustment', sa.Enum('SA', 'SAAR', 'NSA', 'unknown', name='ck_series_seasonal_adjustment', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reference_kind', sa.Enum('index_base', 'constant_prices', 'ppp_base', 'other', name='ck_series_reference_kind', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('reference_label', sa.String(), nullable=True),
    sa.Column('replaced_by_series_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(measure != 'growth') OR measure_horizon IS NOT NULL", name='ck_series_growth_requires_horizon'),
    sa.CheckConstraint("(unit_kind != 'currency') OR currency_code IS NOT NULL", name='ck_series_currency_requires_code'),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_by_series_id'], ['series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_series_code'),
    sa.UniqueConstraint('replaced_by_series_id', name='uq_series_replaced_by_series_id')
    )
    op.create_table('series_families',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('geography_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_series_families_code')
    )
    op.create_table('derived_series',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('formula_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('execution_policy', sa.Enum('scheduled', 'upstream_update', 'manual', name='ck_derived_series_execution_policy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_deterministic', sa.Boolean(), nullable=False),
    sa.Column('requires_vintage_awareness', sa.Boolean(), nullable=False),
    sa.Column('code_ref', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', name='uq_derived_series_series_id')
    )
    op.create_table('series_family_members',
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['series_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'series_id'),
    sa.UniqueConstraint('series_id', name='uq_series_family_members_series_id')
    )
    op.create_table('series_sources',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('provider_catalog_id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(), nullable=False),
    sa.Column('external_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('provider_role', sa.Enum('primary_source', 'redistributor', 'harmonized', 'vendor_estimate', 'internal', 'other', name='ck_series_sources_provider_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('value_transform', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_catalog_id'], ['provider_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_catalog_id', 'external_code', name='uq_series_sources_catalog_external_code')
    )
    op.create_table('series_tags',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    op.create_table('computation_run_logs',
    sa.Column('derived_series_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'partial', 'pending', name='ck_computation_run_logs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rows_computed', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.Enum('scheduler', 'manual', 'backfill', 'upstream_update', name='ck_computation_run_logs_triggered_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('code_version', sa.String(), nullable=True),
    sa.Column('input_vintage_policy', sa.Enum('latest_available', 'vintage_as_of', 'fixed_vintage', 'window_relative', name='ck_computation_run_logs_input_vintage_policy', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('input_vintage_date', sa.Date(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_mode', sa.Enum('write_observations', 'dry_run', 'validation_only', name='ck_computation_run_logs_output_mode', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derived_series_id'], ['derived_series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivation_inputs',
    sa.Column('derived_series_id', sa.UUID(), nullable=False),
    sa.Column('input_series_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derived_series_id'], ['derived_series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_series_id'], ['series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derived_series_id', 'input_series_id', name='uq_derivation_inputs_output_input')
    )
    op.create_table('ingestion_feeds',
    sa.Column('series_source_id', sa.UUID(), nullable=False),
    sa.Column('feed_method', sa.Enum('api', 'file', 'scrape', name='ck_ingestion_feeds_feed_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path_pattern', sa.String(), nullable=True),
    sa.Column('response_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cron_schedule', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_source_id'], ['series_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_run_logs',
    sa.Column('ingestion_feed_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'partial', name='ck_ingestion_run_logs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.Enum('scheduler', 'manual', 'backfill', name='ck_ingestion_run_logs_triggered_by', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('code_version', sa.String(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_feed_id'], ['ingestion_feeds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('vintage_date', sa.Date(), nullable=False),
    sa.Column('ingestion_run_log_id', sa.UUID(), nullable=True),
    sa.Column('computation_run_log_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_observations_period_bounds'),
    sa.ForeignKeyConstraint(['computation_run_log_id'], ['computation_run_logs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_log_id'], ['ingestion_run_logs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'period_start', 'vintage_date', name='uq_observations_series_period_vintage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('ingestion_run_logs')
    op.drop_table('ingestion_feeds')
    op.drop_table('derivation_inputs')
    op.drop_table('computation_run_logs')
    op.drop_table('series_tags')
    op.drop_table('series_sources')
    op.drop_table('series_family_members')
    op.drop_table('derived_series')
    op.drop_table('series_families')
    op.drop_table('series')
    op.drop_table('provider_catalogs')
    op.drop_table('geography_memberships')
    op.drop_table('change_proposal_items')
    op.drop_table('tags')
    op.drop_table('providers')
    op.drop_table('geographies')
    op.drop_table('concepts')
    op.drop_table('change_proposals')
    # ### end Alembic commands ###
