"""Curated V8 category-taxonomy seed data (ADR 0026, within ADR 0025 schema).

Baked at authoring time from the "Seed rows (flat)" tab of
``docs/schema/category_taxonomy.xlsx`` (the source of truth, generated by
``docs/schema/build_category_taxonomy_xlsx.py``). The module carries no runtime
dependency on openpyxl — the rows are Python literals, exactly as
``seed/data/geographies.py`` bakes geographies.

Scope (ADR 0026 §5): seed the topic skeleton — the 15 domains (L1) and 71
subdomains (L2) — plus the handful of *universal* concepts every country
publishes. The long tail of L3 concepts is **not** seeded; it accretes via
bootstrap/onboarding (no placeholder concepts, ADR 0010 / ADR 0026 §5).

Note that 14 of the 71 subdomains are ``kind=concept`` "concept-leaf" L2s
(ADR 0026 §5: an L2 that maps to one economic idea is itself the attachable
concept, e.g. ``FISCAL_BALANCE``, ``EXCHANGE_RATE``). They are seeded with the
subdomain skeleton and are universally attachable in their own right.
"""

from __future__ import annotations

from typing import TypedDict


class CategorySeed(TypedDict, total=False):
    """Seed payload for one category node, with optional parent linkage."""

    code: str
    name: str
    kind: str
    parent_code: str | None


# --- L1 domains (kind=topic, no parent) -------------------------------------
DOMAINS: list[CategorySeed] = [
    {"code": "PRICES", "name": "Prices", "kind": "topic", "parent_code": None},
    {"code": "NATIONAL_ACCOUNTS", "name": "National Accounts", "kind": "topic", "parent_code": None},
    {"code": "PRODUCTION_BUSINESS_ACTIVITY", "name": "Production & Business Activity", "kind": "topic", "parent_code": None},
    {"code": "RETAIL_CONSUMPTION", "name": "Retail & Consumption", "kind": "topic", "parent_code": None},
    {"code": "LABOR", "name": "Labour", "kind": "topic", "parent_code": None},
    {"code": "MONETARY_BANKING", "name": "Monetary & Banking", "kind": "topic", "parent_code": None},
    {"code": "FINANCIAL_INDICATORS", "name": "Financial Indicators", "kind": "topic", "parent_code": None},
    {"code": "GOVERNMENT_FISCAL", "name": "Government & Fiscal", "kind": "topic", "parent_code": None},
    {"code": "INTERNATIONAL", "name": "International / External Sector", "kind": "topic", "parent_code": None},
    {"code": "DEMOGRAPHICS", "name": "Demographics", "kind": "topic", "parent_code": None},
    {"code": "HEALTH", "name": "Health", "kind": "topic", "parent_code": None},
    {"code": "EDUCATION", "name": "Education", "kind": "topic", "parent_code": None},
    {"code": "SOCIETY", "name": "Society & Living Conditions", "kind": "topic", "parent_code": None},
    {"code": "ENVIRONMENT", "name": "Environment", "kind": "topic", "parent_code": None},
    {"code": "OTHER", "name": "Other", "kind": "topic", "parent_code": None},
]


# --- L2 subdomains (kind=topic, except documented concept-leaf L2s) ----------
SUBDOMAINS: list[CategorySeed] = [
    {"code": "CONSUMER_PRICES", "name": "Consumer Prices", "kind": "topic", "parent_code": "PRICES"},
    {"code": "PRODUCER_PRICES", "name": "Producer Prices", "kind": "topic", "parent_code": "PRICES"},
    {"code": "TRADE_PRICES", "name": "Trade Prices", "kind": "topic", "parent_code": "PRICES"},
    {"code": "PROPERTY_PRICES", "name": "Property Prices", "kind": "topic", "parent_code": "PRICES"},
    {"code": "COMMODITY_PRICE", "name": "Commodity Prices", "kind": "concept", "parent_code": "PRICES"},
    {"code": "COMPARATIVE_PRICE_LEVELS", "name": "Comparative Price Levels", "kind": "topic", "parent_code": "PRICES"},
    {"code": "GDP_AND_GROWTH", "name": "GDP & Growth", "kind": "topic", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "EXPENDITURE_COMPONENTS", "name": "Expenditure Components", "kind": "topic", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "INCOME_AND_SAVING", "name": "Income & Saving", "kind": "topic", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "SECTOR_ACCOUNTS", "name": "Sector Accounts", "kind": "topic", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "INPUT_OUTPUT", "name": "Input Output", "kind": "concept", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "NATIONAL_WEALTH", "name": "National Wealth", "kind": "topic", "parent_code": "NATIONAL_ACCOUNTS"},
    {"code": "INDUSTRIAL_PRODUCTION", "name": "Industrial Production", "kind": "topic", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "SECTORAL_OUTPUT", "name": "Sectoral Output", "kind": "concept", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "CONSTRUCTION", "name": "Construction", "kind": "topic", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "BUSINESS_SURVEYS", "name": "Business Surveys", "kind": "topic", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "BUSINESS_DEMOGRAPHY", "name": "Business Demography", "kind": "topic", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "BUSINESS_PROFITS", "name": "Business Profits", "kind": "topic", "parent_code": "PRODUCTION_BUSINESS_ACTIVITY"},
    {"code": "DISTRIBUTIVE_TRADE", "name": "Distributive Trade", "kind": "topic", "parent_code": "RETAIL_CONSUMPTION"},
    {"code": "CONSUMER_CONFIDENCE", "name": "Consumer Confidence", "kind": "concept", "parent_code": "RETAIL_CONSUMPTION"},
    {"code": "HOUSEHOLD_SPENDING", "name": "Household Spending", "kind": "concept", "parent_code": "RETAIL_CONSUMPTION"},
    {"code": "EMPLOYMENT_AND_UNEMPLOYMENT", "name": "Employment & Unemployment", "kind": "topic", "parent_code": "LABOR"},
    {"code": "WAGES_AND_EARNINGS", "name": "Wages & Earnings", "kind": "topic", "parent_code": "LABOR"},
    {"code": "PRODUCTIVITY", "name": "Productivity", "kind": "topic", "parent_code": "LABOR"},
    {"code": "MONETARY_AGGREGATES", "name": "Monetary Aggregates", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "INTEREST_RATES", "name": "Interest Rates", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "CREDIT_AND_DEBT", "name": "Credit & Debt", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "CENTRAL_BANK_BALANCE_SHEET", "name": "Central Bank Balance Sheet", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "BANKING_SECTOR", "name": "Banking Sector", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "FINANCIAL_INCLUSION", "name": "Financial Inclusion", "kind": "topic", "parent_code": "MONETARY_BANKING"},
    {"code": "EQUITY_MARKETS", "name": "Equity Markets", "kind": "topic", "parent_code": "FINANCIAL_INDICATORS"},
    {"code": "BOND_YIELDS_AND_SPREADS", "name": "Bond Yields & Spreads", "kind": "topic", "parent_code": "FINANCIAL_INDICATORS"},
    {"code": "VOLATILITY_AND_RISK", "name": "Volatility & Risk", "kind": "topic", "parent_code": "FINANCIAL_INDICATORS"},
    {"code": "FINANCIAL_CONDITIONS", "name": "Financial Conditions", "kind": "concept", "parent_code": "FINANCIAL_INDICATORS"},
    {"code": "REVENUE_AND_TAXATION", "name": "Revenue & Taxation", "kind": "topic", "parent_code": "GOVERNMENT_FISCAL"},
    {"code": "EXPENDITURE", "name": "Expenditure", "kind": "topic", "parent_code": "GOVERNMENT_FISCAL"},
    {"code": "FISCAL_BALANCE", "name": "Fiscal Balance", "kind": "concept", "parent_code": "GOVERNMENT_FISCAL"},
    {"code": "PUBLIC_DEBT", "name": "Public Debt", "kind": "topic", "parent_code": "GOVERNMENT_FISCAL"},
    {"code": "MERCHANDISE_TRADE", "name": "Merchandise Trade", "kind": "topic", "parent_code": "INTERNATIONAL"},
    {"code": "TRADE_IN_SERVICES", "name": "Trade In Services", "kind": "topic", "parent_code": "INTERNATIONAL"},
    {"code": "BALANCE_OF_PAYMENTS", "name": "Balance Of Payments", "kind": "topic", "parent_code": "INTERNATIONAL"},
    {"code": "EXCHANGE_RATE", "name": "Exchange Rate", "kind": "concept", "parent_code": "INTERNATIONAL"},
    {"code": "RESERVES_AND_INVESTMENT_POSITION", "name": "Reserves & Investment Position", "kind": "topic", "parent_code": "INTERNATIONAL"},
    {"code": "FOREIGN_INVESTMENT", "name": "Foreign Investment", "kind": "topic", "parent_code": "INTERNATIONAL"},
    {"code": "POPULATION_STOCK_AND_STRUCTURE", "name": "Population Stock & Structure", "kind": "topic", "parent_code": "DEMOGRAPHICS"},
    {"code": "VITAL_STATISTICS", "name": "Vital Statistics", "kind": "topic", "parent_code": "DEMOGRAPHICS"},
    {"code": "MIGRATION", "name": "Migration", "kind": "topic", "parent_code": "DEMOGRAPHICS"},
    {"code": "HOUSEHOLDS_AND_FAMILIES", "name": "Households & Families", "kind": "topic", "parent_code": "DEMOGRAPHICS"},
    {"code": "HEALTH_STATUS_AND_OUTCOMES", "name": "Health Status & Outcomes", "kind": "topic", "parent_code": "HEALTH"},
    {"code": "HEALTH_RISK_FACTORS", "name": "Health Risk Factors", "kind": "topic", "parent_code": "HEALTH"},
    {"code": "HEALTH_EXPENDITURE", "name": "Health Expenditure", "kind": "concept", "parent_code": "HEALTH"},
    {"code": "HEALTH_SERVICES", "name": "Health Services", "kind": "topic", "parent_code": "HEALTH"},
    {"code": "ENROLLMENT_AND_PARTICIPATION", "name": "Enrollment & Participation", "kind": "concept", "parent_code": "EDUCATION"},
    {"code": "ATTAINMENT_AND_LITERACY", "name": "Attainment & Literacy", "kind": "topic", "parent_code": "EDUCATION"},
    {"code": "EDUCATION_EXPENDITURE", "name": "Education Expenditure", "kind": "concept", "parent_code": "EDUCATION"},
    {"code": "EDUCATION_OUTCOMES", "name": "Education Outcomes", "kind": "topic", "parent_code": "EDUCATION"},
    {"code": "INCOME_AND_INEQUALITY", "name": "Income & Inequality", "kind": "topic", "parent_code": "SOCIETY"},
    {"code": "CRIME_AND_JUSTICE", "name": "Crime & Justice", "kind": "topic", "parent_code": "SOCIETY"},
    {"code": "SOCIAL_PROTECTION", "name": "Social Protection", "kind": "topic", "parent_code": "SOCIETY"},
    {"code": "CULTURE_AND_RECREATION", "name": "Culture & Recreation", "kind": "topic", "parent_code": "SOCIETY"},
    {"code": "WELLBEING", "name": "Wellbeing", "kind": "concept", "parent_code": "SOCIETY"},
    {"code": "HOUSING_CONDITIONS", "name": "Housing Conditions", "kind": "topic", "parent_code": "SOCIETY"},
    {"code": "BASIC_SERVICES_ACCESS", "name": "Basic Services Access", "kind": "concept", "parent_code": "SOCIETY"},
    {"code": "EMISSIONS_AND_AIR_QUALITY", "name": "Emissions & Air Quality", "kind": "topic", "parent_code": "ENVIRONMENT"},
    {"code": "NATURAL_RESOURCES", "name": "Natural Resources", "kind": "topic", "parent_code": "ENVIRONMENT"},
    {"code": "CLIMATE", "name": "Climate", "kind": "topic", "parent_code": "ENVIRONMENT"},
    {"code": "ENERGY", "name": "Energy", "kind": "topic", "parent_code": "OTHER"},
    {"code": "SCIENCE_AND_TECHNOLOGY", "name": "Science & Technology", "kind": "topic", "parent_code": "OTHER"},
    {"code": "TOURISM", "name": "Tourism", "kind": "topic", "parent_code": "OTHER"},
    {"code": "TRANSPORT", "name": "Transport", "kind": "topic", "parent_code": "OTHER"},
    {"code": "UNCLASSIFIED", "name": "Unclassified", "kind": "concept", "parent_code": "OTHER"},
]


# --- Universal L3 concepts (kind=concept) -----------------------------------
# The headline measures every country publishes (ADR 0026 §5: "the handful of
# universal concepts every country has ... let the long tail accrete via
# onboarding"). GDP maps to the two universal-headline tiers GDP_REAL and
# GDP_NOMINAL (there is no bare GDP concept in the V8 tree).
UNIVERSAL_CONCEPTS: list[CategorySeed] = [
    {"code": "CPI_ALL_ITEMS", "name": "CPI All Items", "kind": "concept", "parent_code": "CONSUMER_PRICES"},
    {"code": "GDP_NOMINAL", "name": "GDP Nominal", "kind": "concept", "parent_code": "GDP_AND_GROWTH"},
    {"code": "GDP_REAL", "name": "GDP Real", "kind": "concept", "parent_code": "GDP_AND_GROWTH"},
    {"code": "UNEMPLOYMENT_RATE", "name": "Unemployment Rate", "kind": "concept", "parent_code": "EMPLOYMENT_AND_UNEMPLOYMENT"},
    {"code": "BROAD_MONEY", "name": "Broad Money", "kind": "concept", "parent_code": "MONETARY_AGGREGATES"},
    {"code": "POLICY_RATE", "name": "Policy Rate", "kind": "concept", "parent_code": "INTEREST_RATES"},
    {"code": "GENERAL_GOVERNMENT_DEBT", "name": "General Government Debt", "kind": "concept", "parent_code": "PUBLIC_DEBT"},
    {"code": "CURRENT_ACCOUNT_BALANCE", "name": "Current Account Balance", "kind": "concept", "parent_code": "BALANCE_OF_PAYMENTS"},
    {"code": "TOTAL_POPULATION", "name": "Total Population", "kind": "concept", "parent_code": "POPULATION_STOCK_AND_STRUCTURE"},
]


# All seeded nodes, in tree order (domains, then subdomains, then universal
# concepts). The seed runner relies on this ordering: a node's parent always
# appears before it, so edges resolve in one forward pass.
CATEGORIES: list[CategorySeed] = [*DOMAINS, *SUBDOMAINS, *UNIVERSAL_CONCEPTS]


__all__ = [
    "CATEGORIES",
    "DOMAINS",
    "SUBDOMAINS",
    "UNIVERSAL_CONCEPTS",
    "CategorySeed",
]
